import Head from "next/head";
import Home1 from "../components/Home";

export default function Home({ costs }) {
  return (
    <div className="w-full h-full bg-light">
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home1 data={costs} />
    </div>
  );
}

// export async function getStaticProps() {
//   // do your logic
//   const data = await fetch(
//     "https://money-manager-e3253-default-rtdb.firebaseio.com/costs.json"
//   )
//     .then(async (res) => {
//       const data = await res.json();
//       return data;
//     })
//     .catch((e) => {
//       console.log(e);
//     });

//   return { props: {
//     costs: data },
//   revalidate: 3600 };
// }

export async function getServerSideProps() {
  const data = await fetch("/api/costs")
    .then(async (res) => {
      const data = await res.json();
      if (data && data.message && data.message === "Not found") {
        return [];
      }
      return data;
    })
    .catch((e) => {
      console.log(e);
      return [];
    });

  return { props: { costs: data } };
}

// {
//   method: "POST",
//   body: JSON.stringify({ title: "some teztasdhf" }),
//   headers: {
//     "Content-Type": "application/json",
//     // 'Content-Type': 'application/x-www-form-urlencoded',
//   },
// }
